"AI-driven strategy execution directly on MetaTrader 5, 24/5, with configurable risk rails.": "تنفيذٌ للاستراتيجيات مدفوعٌ بالـ AI مباشرةً على MetaTrader 5، على مدار 24/5، مع حدود مخاطر قابلة للضبط.",
"Strategy creators and data providers earn WFB for contributions traded on the marketplace.": "يكتسب منشئو الاستراتيجيات وموفّرو البيانات WFB مقابل مساهماتهم المتداولة في السوق.",
"Least-privilege access, multi-sig controls, and continuous monitoring across all services.": "وصولٌ بأقلّ الصلاحيات، وضوابط متعدّدة التوقيع، ومراقبةٌ متواصلة عبر جميع الخدمات.",
"Bounties, ambassador rewards, and competition prizes distributed in WFB to active members.": "مكافآت استكشاف الأخطاء، ومكافآات السفراء، وجوائز المسابقات تُوزَّع في WFB للأعضاء النشطين.",
"Seven diversified streams feed the ecosystem treasury, each denominated or settled in WFB.": "سبعة مصادر متنوّعة تُغذّي خزانة النظام البيئي، يُحدَّد كلٌّ منها أو يُسوَّى بوحدات WFB.",
"A closer look at how capital systematically drains from retail trading participants today.": "نظرةٌ أعمق على كيفية استنزاف رأس المال بشكل منهجي من المشاركين في التداول التجزئي اليوم.",
"From market data to executed position: the intelligence pipeline that powers W Forex Bot.": "من بيانات السوق إلى المركز المنفَّذ: خطُ المعالجة الاستخباراتي الذي يُحرّك W Forex Bot.",
"Conversational intelligence for strategy selection, market context, and decision support.": "ذكاءٌ حواري لاختيار الاستراتيجيات، وفهم سياق السوق، ودعم اتخاذ القرار.",
"Full transparency on what could go wrong, and the mitigation philosophy behind each risk.": "شفافيةٌ كاملة عمّا قد يسوء، وفلسفة التخفيف الكامنة وراء كل خطر.",
"A layered stack where AI, execution, and on-chain settlement move as one coherent system.": "حزمةٌ متعدّدة الطبقات يتحرّك فيها الـ AI والتنفيذ والتسوية on-chain كنظامٍ واحدٍ متناسق.",
"WFB holders propose and vote on platform parameters, fee models, and treasury allocation.": "يُقدّم حاملو WFB المقترحات ويُصوّتون على معطيات المنصّة ونماذج الرسوم وتخصيص الخزانة.",
"Stake WFB to earn protocol yield, unlock higher tiers, and access early product releases.": "ارهن WFB لتكسب عائد البروتوكول، وتفتح مستويات أعلى، وتنفرد بالوصول المبكر إلى إصدارات المنتجات.",
"A fast-maturing asset class demanding institutional-grade automation and risk controls.": "فئةُ أصولٍ سريعة النضج تتطلّب أتمتةً وضوابط مخاطر بمستوى مؤسسي.",
"Figures are illustrative, drawn from public industry estimates. Not investment advice.": "الأرقام استرشادية، مستمدّة من تقديرات الصناعة العامة. وهي ليست استشارة استثمارية.",
"Self-custodial wallet for holding, staking, and transacting WFB and supported assets.": "محفظةُ حفظٍ ذاتي لحفظ WFB والأصول المدعومة ورهنها والتداول بها.",
"Buy and sell strategies, signals, and datasets; creators earn WFB for contributions.": "شراء وبيع الاستراتيجيات والإشارات ومجموعات البيانات؛ ويكسب المنشئون WFB مقابل مساهماتهم.",
"Stateless services, horizontal scaling, and BNB Chain's high-throughput settlement.": "خدماتٌ عديمة الحالة، وتوسّعٌ أفقي، وتسويةٌ عالية الإنتاجية عبر BNB Chain.",
"— every interaction within the ecosystem settles, rewards, or is discounted in WFB.": "كلّ تفاعلٍ داخل النظام البيئي يُسوَّى، أو يُكافأ، أو يُخصَّم بوحدات WFB.",
"An audience that already understands self-custody, tokens, and aligned incentives.": "جمهورٌ يفهم بالفعل الحفظ الذاتي والرموز والحوافز المتّسقة.",
"Native mobile experience: monitor, manage, and act on the ecosystem from anywhere.": "تجربةٌ أصلية على الجوّال: راقب وأدِر وتصرّف في النظام البيئي من أيّ مكان.",
"Real-time performance, exposure, and risk analytics, with transparency by default.": "تحليلاتٌ فورية للأداء والتعرّض والمخاطر، مع شفافيةٍ افتراضية.",
"Open APIs, bounties, and grants attract builders creating on WFB infrastructure.": "واجهات API مفتوحة، ومكافآت استكشاف الأخطاء، ومنحٌ تجذب البانين الذين يُنشئون على بنية WFB.",
"Governance, education, and incentive programs that align and grow the user base.": "برامجُ حوكمة وتعليم وحوافز تُحقّق الانسجام وتُنمّي قاعدة المستخدمين.",
"All figures illustrative and editable prior to the final token generation event.": "جميع الأرقام استرشادية وقابلة للتعديل قبل حدث توليد الرمز النهائي.",
"Advanced AI model access, custom strategy generation, and priority intelligence.": "وصولٌ متقدّم إلى نماذج الـ AI، وتوليدٌ مخصّص للاستراتيجيات، واستخباراتٌ ذات أولوية.",
"Tiered monthly & annual plans for bot access, paid in WFB at a native discount.": "خططٌ شهرية وسنوية متدرّجة للوصول إلى البوت، تُدفع بوحدات WFB بخصمٍ أصلي.",
"Platform fee on every strategy, signal, and dataset sold between participants.": "رسومٌ منصّة على كل استراتيجية وإشارة ومجموعة بيانات تُباع بين المشاركين.",
"Multi-tier on-chain referral system rewarding active participant acquisition.": "نظامُ إحالات متعدّد المستويات على on-chain يُكافئ الاستحواذ النشط على المشاركين.",
"Each component of the WFB ecosystem and the role it plays in the value loop.": "كلّ مكوّنٍ من النظام البيئي لـ WFB والدور الذي يضطلع به في حلقة القيمة.",
", turning users into stakeholders and friction into value they actually own.": "، فتُحوِّل المستخدمين إلى أصحاب مصلحة، والتعب إلى قيمةٍ يملكونها فعلاً.",
"Forex and crypto markets are volatile; trading can result in capital loss.": "أسواق الفوركس والعملات الرقمية متقلّبة؛ وقد يُؤدّي التداول إلى خسارة رأس المال.",
"— a share of marketplace & premium fees permanently removed from supply.": "حصّةٌ من رسوم السوق والرسوم المميّزة تُزال بشكلٍ دائم من العرض.",
"White-label and institutional licenses for funds, brokers, and fintechs.": "ترخيصاتٌ ذات علامة بيضاء ومؤسسية للصناديق والوسطاء وشركات التكنولوجيا المالية.",
"Votes on protocol decisions and compounds rewards as the network scales.": "يُصوّت على قرارات البروتوكول وتتضاعف مكافآته مع نموّ الشبكة.",
"An overview of what WFB Token is, why it exists, and where it is going.": "نظرةٌ عامة على ماهية WFB Token، ولماذا وُجد، وإلى أين يتّجه.",
"Pays for a subscription, deploys a strategy, or stakes to unlock tiers.": "يدفع ثمن اشتراك، أو ينشر استراتيجية، أو يرهن لفتح المستويات.",
"Obtains WFB on a DEX/CEX to access the ecosystem at a native discount.": "يحصل على WFB عبر DEX/CEX للوصول إلى النظام البيئي بخصمٍ أصلي.",
"Metered API & data access for developers building on WFB intelligence.": "وصولٌ مقيس إلى API والبيانات للمطوّرين البانين على ذكاء WFB.",
"Token Generation Event — the creation and initial distribution of WFB.": "حدث توليد الرمز: إنشاء WFB وتوزيعه الأوّلي.",
"Strategic integrations, co-marketing, and listed-venue revenue shares.": "تكاملاتٌ استراتيجية، وتسويقٌ مشترك، وحصصٌ من إيرادات الأماكن المُدرجة.",
"Roadmap milestones may shift; not all features may ship as described.": "قد تتغيّر معالم خارطة الطريق؛ وقد لا تُطلق كل الميزات كما هو موصوف.",
"The market is crowded; incumbents and new entrants compete for users.": "السوق مزدحم؛ ويتنافس القائمون والوافدون الجدد على المستخدمين.",
"can realign platforms and users. WFB sits at the convergence of both.": "تستطيع إعادة مواءمة المنصّات والمستخدمين. ويقع WFB عند تقاطع كليهما.",
"automation that puts participants on the same side as the platform.\"": "أتمتةٌ تضع المشاركين في الجانب نفسه الذي تقف فيه المنصّة.",
"unified risk engine, configurable drawdown limits, position sizing.": "محرّكُ مخاطر موحّد، وحدودٌ قابلة للضبط للاسحباط، وتحديدٌ لحجم المراكز.",
"— the largest share rewards the participants who build the network.": "الحصةُ الأكبر تُكافئ المشاركين الذين يبنون الشبكة.",
"jurisdiction-aware design, legal counsel, compliance-first posture.": "تصميمٌ واعٍ بالاختصاص القضائي، واستشاراتٌ قانونية، وموقفٌ يضع الامتثال أوّلاً.",
"Native utility token of the W Forex Bot ecosystem, BEP-20 standard.": "الرمز المنفعي الأصلي للنظام البيئي لـ W Forex Bot، وفق معيار BEP-20.",
"Smart contracts, keys, and infrastructure are targets for attack.": "العقود الذكية والمفاتيح والبنية التحتية أهدافٌ للهجوم.",
"Earns WFB via referrals, the marketplace, or community programs.": "يكسب WFB عبر الإحالات أو السوق أو برامج المجتمع.",
"Software bugs, model drift, or infrastructure failure may occur.": "قد تحدث أخطاء برمجية، أو انجرافٌ في النماذج، أو إخفاقاتٌ في البنية التحتية.",
"Figures illustrative. Forex volume: BIS Triennial Survey (2022).": "الأرقام استرشادية. حجم الفوركس: مسح BIS الثلاثي (2022).",
"A unified system enforcing exposure, drawdown, and sizing rules.": "نظامٌ موحّد يُطبّق قواعد التعرّض والاسحباط وتحديد الحجم.",
"Digital-asset regulation varies by jurisdiction and is evolving.": "تنظيمُ الأصول الرقمية يختلف باختلاف الاختصاص القضائي وهو في تطوّر مستمر.",
"A wallet requiring multiple signers to authorize a transaction.": "محفظةٌ تتطلّب عدّة مُوقِّعين لتصرّح بمعاملة.",
"Key terms used throughout this whitepaper, defined for clarity.": "المصطلحات الأساسية المستخدمة في هذه الورقة البيانية، مُعرَّفة لتوضيح المعنى.",
"Encounters W Forex Bot via community, referral, or marketplace.": "يتعرّف على W Forex Bot عبر المجتمع أو الإحالة أو السوق.",
"phased delivery, transparent reporting, community governance.": "تسليمٌ مرحلي، و تقارير شفافة، وحوكمةٌ مجتمعية.",
"— generous launch liquidity reduces volatility and slippage.": "سيولةُ الإطلاق السخية تُقلّل من التقلّب والانزلاق السعري.",
"Time-locked release of tokens to align long-term commitment.": "إطلاقٌ مُؤجّل زمنياً للرموز لإرساء التزامٍ طويل الأمد.",
"From AI expansion to global scale: the long-horizon vision.": "من توسّع الـ AI إلى النطاق العالمي: الرؤية بعيدة المدى.",
"— team & reserve locked to align with multi-year delivery.": "فريقٌ واحتياطي مُقفَلان لإرساء الانسجام مع تسليمٍ يمتدّ لسنوات.",
"convergence moat: AI + MT5 + on-chain + tokenized rewards.": "خندقُ التقارب: الـ AI + MT5 + on-chain + مكافآتٌ مُرمَّزة.",
"audits, multi-sig, cold storage, bug bounties, monitoring.": "تدقيقات، وتوقيعٌ متعدّد، وتخزينٌ بارد، ومكافآت لاكتشاف الأخطاء، ومراقبة.",
"— treasury-funded buybacks redistribute value to stakers.": "عملياتُ إعادة الشراء المموّلة من الخزانة تُعيد توزيع القيمة على المُراهنين.",
"The intelligence and cloud backbone powering W Forex Bot.": "العمودُ الفقري الاستخباراتي والسحابي الذي يُحرّك W Forex Bot.",
"— staking & tiered membership remove circulating supply.": "الرهنُ والعضوية المتدرّجة تُزيلان المعروض المتداول.",
"— executing a strategy without fear, greed, or fatigue.": "تنفيذُ استراتيجيةٍ بلا خوف ولا طمع ولا إرهاق.",
"One Ecosystem  ·  One Token  ·  Unlimited Possibilities": "نظامٌ بيئي واحد  ·  رمزٌ واحد  ·  إمكاناتٌ لا حصر لها",
"— governance and staking convert users to stakeholders.": "الحوكمةُ والرهن يُحوّلان المستخدمين إلى أصحاب مصلحة.",
"across vast multi-year datasets no human could process.": "عبر مجموعات بياناتٍ هائلة ممتدة لسنوات لا يستطيع بشريٌّ معالجتها.",
"A snapshot of the opportunity WFB is built to capture.": "لمحةٌ عن الفرصة التي صُمِّم WFB لاقتناصها.",
"MetaTrader 5 — a leading multi-asset trading platform.": "MetaTrader 5: منصّةُ تداولٍ متعدّدة الأصول رائدة.",
"On-chain voting by WFB holders on protocol decisions.": "تصويتٌ على on-chain يجريه حاملو WFB على قرارات البروتوكول.",
"WFB Token — Whitepaper · The AI-Powered Utility Token": "WFB Token: الورقة البيانية · الرمز المنفعي المدفوع بالـ AI",
"Latency-driven gap between expected and fill price.": "الفجوةُ الناتجة عن زمن الاستجابة بين السعر المتوقّع وسعر التنفيذ.",
"One Ecosystem · One Token · Unlimited Possibilities": "نظامٌ بيئي واحد · رمزٌ واحد · إمكاناتٌ لا حصر لها",
"intelligent, transparent, properly aligned trading.": "تداولٌ ذكي وشفاف ومنسجمٌ على النحو الصحيح.",
"Every module settles, rewards, or is discounted in": "كلّ وحدةٍ تُسوَّى، أو تُكافأ، أو تُخصَّم بوحدات",
"Recurring platform costs with no equity or upside.": "تكاليفُ منصّة متكرّرة بلا حقوق ملكية أو عوائد صاعدة.",
"— on-chain settlement and verifiable performance.": "تسويةٌ على on-chain وأداءٌ قابل للتحقّق.",
"— converting cost into owned, compounding value.": "تحويلُ التكلفة إلى قيمةٍ مملوكة تتضاعف.",
"audits, monitoring, redundancy, staged rollouts.": "تدقيقات، ومراقبة، وتكرارٌ احتياطي، وإطلاقاتٌ متدرّجة.",
"— native token discounts vs. fiat subscriptions.": "خصوماتٌ أصليّة بالرمز مقابل الاشتراكات بالعملة الورقية.",
"The token is not a speculative instrument; it is": "الرمزُ ليس أداةً مضاربية؛ بل هو",
"\"We didn’t set out to build just another token.": "«لم ننطلق لنبنو مجرّد رمزٍ آخر.",
"— reacting in milliseconds across 24/5 markets.": "ردُّ فعلٍ بالملي ثانية عبر أسواق 24/5.",
"— AI-driven execution across Forex and crypto.": "تنفيذٌ مدفوعٌ بالـ AI عبر الفوركس والعملات الرقمية.",
"— risk parameters still require human intent.": "معطياتُ المخاطر لا تزال تتطلّب نيّةً بشريّة.",
"— retraining against shifting market regimes.": "إعادةُ تدريبٍ في مواجهة أنظمة السوق المتغيّرة.",
"Emotional, fatigued, or mistimed decisions.": "قراراتٌ عاطفية أو منهكة أو في توقيتٍ خاطئ.",
"Opaque markups embedded in every execution.": "هوامشُ معتمة مدمجة في كل تنفيذ.",
"Locking WFB to earn yield and unlock tiers.": "قفلُ WFB لكسب العائد وفتح المستويات.",
"; edge improves probability, not certainty.": "؛ فالأفضليّة ترفع الاحتمال، لا اليقين.",
"— markets carry inherent, irreducible risk.": "الأسواقُ تحمل مخاطرَ جوهرية لا تُختزل.",
"— black-swan events remain unforecastable.": "أحداثُ البجع الأسود تبقى غير قابلة للتنبّؤ.",
"BEP-20 Smart Contract · Multi-sig Treasury": "عقدٌ ذكي BEP-20 · خزانةٌ متعدّدة التوقيع",
"— value flows inward and radiates outward.": "القيمةُ تتدفّق إلى الداخل وتشعُّ إلى الخارج.",
"— Partial / depends   ·   ✕ Not available": "جزئي / يعتمد   ·   ✕ غير متاح",
